const { resolve } = require('path');

const packagePath = resolve(process.cwd(), 'package.json');
const { publishConfig = { registry: null } } = require(packagePath);

const message = 'build: release <%= nextRelease.version %>\n\nComment automatically generated by BOT. Working 24/7 💻🤖\n\n[skip ci]';
const plugins = [
  '@semantic-release/commit-analyzer',
  '@semantic-release/release-notes-generator',
  '@semantic-release/changelog',
  '@semantic-release/github',
  publishConfig.registry ? '@semantic-release/npm' : null,
  [
    '@semantic-release/git',
    {
      message,
      assets: [
        'package.json',
        'CHANGELOG.md',
      ],
    },
  ],
].filter((plugin) => plugin);

module.exports = {
  plugins,
  tagFormat: '<%= version %>',
  branches: [
    'master',
    {
      name: 'beta',
      prerelease: true,
    },
    {
      name: 'alpha',
      prerelease: true,
    },
  ],
};
