name: promote-prod-semantic-release-config

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Promote production release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ env.GITHUB_TOKEN }}
        run: |
          npm install @semantic-release/{changelog,git} --no-save
          npx semantic-release
