name: promote-prod-from-dev

on:
  push:
    branches:
      - master
      - staging
      - beta
      - alpha

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get actions
        uses: actions/checkout@v2
        with:
          repository: pontte/james
          ref: master
          token: ${{ secrets.GH_TOKEN }}
          path: ./.github/actions/james
      - name: Run James
        uses: ./.github/actions/james
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_CONFIG_TOKEN }}
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_CONFIG_PUBLISH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.SEMANTIC_RELEASE_CONFIG_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SEMANTIC_RELEASE_CONFIG_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SEMANTIC_RELEASE_CONFIG_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SEMANTIC_RELEASE_CONFIG_BOT_EMAIL }}
